basePath: /
definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:9999
info:
  contact: {}
  description: API Server for Template Application
  title: Template App API
  version: "1.0"
paths:
  /api/test/:
    get:
      consumes:
      - application/json
      description: test handler
      operationId: testingID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Test
      tags:
      - Test
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
